spring.application.name=Loan_Project



# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/loan_project
spring.datasource.username=root
spring.datasource.password={DB PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adishaikh6400@gmail.com
spring.mail.password={APP MAIL PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true